// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4XQN5egJLVDDghUx8kAY9AGbhwDkjedw',
    appId: '1:560817426212:web:2e35ac4514db4a506fadb1',
    messagingSenderId: '560817426212',
    projectId: 'bulk-sms-paid-numbers',
    authDomain: 'bulk-sms-paid-numbers.firebaseapp.com',
    databaseURL: 'https://bulk-sms-paid-numbers-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bulk-sms-paid-numbers.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMC-VsCqmolFOROtF4qlP7IS0Eozm0TKU',
    appId: '1:560817426212:android:c7e949cfd3dabe106fadb1',
    messagingSenderId: '560817426212',
    projectId: 'bulk-sms-paid-numbers',
    databaseURL: 'https://bulk-sms-paid-numbers-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bulk-sms-paid-numbers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU-q2zIkp46197pIpnKOFbeH3chyA9Nmc',
    appId: '1:560817426212:ios:a6f2427bdf1e84316fadb1',
    messagingSenderId: '560817426212',
    projectId: 'bulk-sms-paid-numbers',
    databaseURL: 'https://bulk-sms-paid-numbers-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bulk-sms-paid-numbers.appspot.com',
    iosBundleId: 'com.example.smsMessagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU-q2zIkp46197pIpnKOFbeH3chyA9Nmc',
    appId: '1:560817426212:ios:2999e1525899568b6fadb1',
    messagingSenderId: '560817426212',
    projectId: 'bulk-sms-paid-numbers',
    databaseURL: 'https://bulk-sms-paid-numbers-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bulk-sms-paid-numbers.appspot.com',
    iosBundleId: 'com.example.smsMessagingApp.RunnerTests',
  );
}
